// Generate mock flight data
const generateTime = (hours, minutes) => {
  const date = new Date();
  date.setHours(hours);
  date.setMinutes(minutes);
  date.setSeconds(0);
  return date;
};
// Calculate actual departure time based on scheduled and status
const calculateActualDeparture = (scheduled, status, delay = 0) => {
  if (status !== 'departed') return null;
  const actual = new Date(scheduled);
  // Random variation: -15 mins (early) to +30 mins (late)
  const variation = delay || Math.floor(Math.random() * 46) - 15;
  actual.setMinutes(actual.getMinutes() + variation);
  return actual;
};
export const mockFlights = [{
  id: 1,
  airline: 'Air Canada',
  operator: 'mainline',
  flightNumber: 'AC 1234',
  destination: 'New York',
  destinationCode: 'JFK',
  gate: 'A1',
  scheduledDeparture: generateTime(8, 30),
  actualDeparture: calculateActualDeparture(generateTime(8, 30), 'departed', -10),
  status: 'departed',
  boardedPassengers: 156,
  totalPassengers: 156,
  loadingProgress: 100,
  totalBags: 120,
  loadedBags: 120,
  delayReason: null,
  aircraftType: 'A320',
  isWideBody: false,
  isInternational: true,
  flightType: 'transborder'
}, {
  id: 2,
  airline: 'Air Canada Rouge',
  operator: 'rouge',
  flightNumber: 'AC 5678',
  destination: 'London',
  destinationCode: 'LHR',
  gate: 'B2',
  scheduledDeparture: generateTime(9, 15),
  actualDeparture: null,
  status: 'boarding',
  boardedPassengers: 198,
  totalPassengers: 305,
  loadingProgress: 80,
  totalBags: 180,
  loadedBags: 145,
  delayReason: null,
  aircraftType: 'Boeing 777',
  isWideBody: true,
  isInternational: true,
  flightType: 'international'
}, {
  id: 3,
  airline: 'Air Canada',
  operator: 'mainline',
  flightNumber: 'AC 9012',
  destination: 'Tokyo',
  destinationCode: 'HND',
  gate: 'C3',
  scheduledDeparture: generateTime(10, 0),
  actualDeparture: null,
  status: 'delayed',
  boardedPassengers: 0,
  totalPassengers: 298,
  loadingProgress: 0,
  totalBags: 200,
  loadedBags: 0,
  delayReason: 'Aircraft technical issue',
  aircraftType: 'Boeing 787',
  isWideBody: true,
  isInternational: true,
  flightType: 'international'
}, {
  id: 4,
  airline: 'Air Canada Jazz',
  operator: 'jazz',
  flightNumber: 'AC 3456',
  destination: 'Montreal',
  destinationCode: 'YUL',
  gate: 'D4',
  scheduledDeparture: generateTime(10, 45),
  actualDeparture: calculateActualDeparture(generateTime(10, 45), 'departed', 0),
  status: 'departed',
  boardingProgress: 100,
  loadingProgress: 100,
  totalBags: 150,
  loadedBags: 150,
  delayReason: null,
  aircraftType: 'A320',
  isWideBody: false,
  isInternational: true,
  flightType: 'domestic'
}, {
  id: 5,
  airline: 'Air Canada',
  operator: 'mainline',
  flightNumber: 'AC 7890',
  destination: 'Vancouver',
  destinationCode: 'YVR',
  gate: 'E5',
  scheduledDeparture: generateTime(11, 30),
  actualDeparture: null,
  status: 'boarding',
  boardedPassengers: 0,
  totalPassengers: 180,
  loadingProgress: 45,
  totalBags: 160,
  loadedBags: 72,
  delayReason: null,
  aircraftType: 'A321',
  isWideBody: false,
  isInternational: false,
  flightType: 'domestic'
}, {
  id: 6,
  airline: 'Air Canada',
  operator: 'mainline',
  flightNumber: 'AC 2468',
  destination: 'Dubai',
  destinationCode: 'DXB',
  gate: 'F6',
  scheduledDeparture: generateTime(12, 15),
  actualDeparture: null,
  status: 'scheduled',
  boardingProgress: 0,
  loadingProgress: 0,
  totalBags: 100,
  loadedBags: 0,
  delayReason: null,
  aircraftType: 'Boeing 737',
  isWideBody: false,
  isInternational: true,
  flightType: 'international'
}, {
  id: 7,
  airline: 'Air Canada',
  operator: 'mainline',
  flightNumber: 'AC 1357',
  destination: 'Singapore',
  destinationCode: 'SIN',
  gate: 'G7',
  scheduledDeparture: generateTime(13, 0),
  actualDeparture: calculateActualDeparture(generateTime(13, 0), 'departed', 15),
  status: 'departed',
  boardingProgress: 100,
  loadingProgress: 100,
  totalBags: 180,
  loadedBags: 180,
  delayReason: null,
  aircraftType: 'A320',
  isWideBody: false,
  isInternational: true,
  flightType: 'international'
}, {
  id: 8,
  airline: 'Air Canada',
  operator: 'mainline',
  flightNumber: 'AC 8642',
  destination: 'Amsterdam',
  destinationCode: 'AMS',
  gate: 'H8',
  scheduledDeparture: generateTime(13, 45),
  actualDeparture: null,
  status: 'delayed',
  boardingProgress: 0,
  loadingProgress: 0,
  totalBags: 120,
  loadedBags: 0,
  delayReason: 'Weather conditions at destination',
  aircraftType: 'Boeing 777',
  isWideBody: true,
  isInternational: true,
  flightType: 'international'
}, {
  id: 9,
  airline: 'Air Canada',
  operator: 'mainline',
  flightNumber: 'AC 9753',
  destination: 'Rome',
  destinationCode: 'FCO',
  gate: 'J9',
  scheduledDeparture: generateTime(14, 30),
  actualDeparture: null,
  status: 'scheduled',
  boardingProgress: 0,
  loadingProgress: 0,
  totalBags: 150,
  loadedBags: 0,
  delayReason: null,
  aircraftType: 'Boeing 787',
  isWideBody: true,
  isInternational: true,
  flightType: 'international'
}, {
  id: 10,
  airline: 'Air Canada',
  operator: 'mainline',
  flightNumber: 'AC 3141',
  destination: 'Los Angeles',
  destinationCode: 'LAX',
  gate: 'K10',
  scheduledDeparture: generateTime(15, 15),
  actualDeparture: null,
  status: 'scheduled',
  boardingProgress: 0,
  loadingProgress: 0,
  totalBags: 100,
  loadedBags: 0,
  delayReason: null,
  aircraftType: 'A320',
  isWideBody: false,
  isInternational: true,
  flightType: 'domestic'
}];